---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fuseml-core
  namespace: fuseml-core
---
# Give the admin rights to ServiceAccount, so it can
# delete various resources forming FuseML applications
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fuseml-core-admin-binding
  namespace: fuseml-workloads
subjects:
  - kind: ServiceAccount
    name: fuseml-core
    namespace: fuseml-core
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fuseml-core
  namespace: fuseml-core
  labels:
    app.kubernetes.io/name: fuseml-core
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: fuseml-core
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fuseml-core
    spec:
      serviceAccountName: fuseml-core
      containers:
      - name: fuseml-core
        image: ghcr.io/fuseml/fuseml-core:latest
        env:
          - name: GITEA_USERNAME
            valueFrom:
              secretKeyRef:
                key: GITEA_USERNAME
                name: fuseml-core-gitea
          - name: GITEA_PASSWORD
            valueFrom:
              secretKeyRef:
                key: GITEA_PASSWORD
                name: fuseml-core-gitea
          - name: GITEA_URL
            value: __GITEA_URL__
          - name: TEKTON_DASHBOARD_URL
            value: __TEKTON_DASHBOARD_URL__
        ports:
        - containerPort: 80
---        
apiVersion: v1
kind: Service
metadata:
  name: fuseml-core
  namespace: fuseml-core
  labels:
    app.kubernetes.io/name: fuseml-core
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app.kubernetes.io/name: fuseml-core
