name: get-fuseml-installer.yml
on:
  push:
    branches:
      - main

jobs:
  Test:
    runs-on: ${{ matrix.os }}
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - if: matrix.os == 'macos-latest'
        name: Install kubectl
        run: brew install kubectl
      - id: measurement-2
        name: Record Measurement After Install kubectl
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install kubectl
          task: get-measurement
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download latest fuseml-installer version
        run: ./install.sh
        shell: bash
      - id: measurement-5
        name: Record Measurement After Download latest fuseml-installer version
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Download latest fuseml-installer version
          task: get-measurement
      - name: Check fuseml-installer version
        run: fuseml-installer -v
      - id: measurement-7
        name: Record Measurement After Check fuseml-installer version
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Check fuseml-installer version
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption1
          path: total_energy_consumption1.json
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
