name: Lint Commit Messages

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
      - name: Setup gitlint
        run: sudo apt-get install gitlint
      - name: Checkout
        run: git clone https://github.com/fuseml/fuseml.git && cd fuseml && git checkout ${GITHUB_HEAD_REF}
      - name: Lint new commits
        working-directory: ./fuseml
        run: gitlint --commits "origin..HEAD"
