name: release.yml

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: fuseml/fuseml/.github/workflows/ci.yml@main

  release:
    name: Release
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - id: branch
        name: Fetch Branch
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw##*/}
          echo "::set-output name=BRANCH_NAME::$branch"

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Setup Ginkgo Test Framework
        run: go install github.com/onsi/ginkgo/ginkgo

      - name: Build FuseML
        run: make release

      - name: Generate Changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          onlyLastTag: "true"
          pullRequests: "false"
          issuesWoLabels: "true"
          stripGeneratorNotice: "true"
          stripHeaders: "true"

      - name: Release FuseML
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: ./CHANGELOG.md
          files: ./dist/*
          prerelease: "true"

      - name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results

      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json

      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption2
          path: total_energy_consumption2.json

  docker-image:
    name: Docker image
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Setup Ginkgo Test Framework
        run: go install github.com/onsi/ginkgo/ginkgo

      - name: Set image name and tag
        run: |
          case "${GITHUB_REF}" in
            refs/heads/main)
              TAG="dev"
              ;;
            refs/tags/v*)
              TAG=${GITHUB_REF/refs\/tags\//}
              ;;
            *)
              TAG=${GITHUB_REF/refs\/*\//}
              ;;
          esac
          echo "IMG=ghcr.io/fuseml/fuseml-installer:${TAG}" >> $GITHUB_ENV

      - name: Build image
        run: make docker-build

      - name: Push image
        run: make docker-push

      - name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results

      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json

      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption3
          path: total_energy_consumption3.json

  fetch-installer:
    needs: release
    uses: fuseml/fuseml/.github/workflows/get-fuseml-installer.yml@main
